name = "search"
main = "src/index.js"
compatibility_date = "2025-06-01"

[assets]
directory = "./public"
binding = "ASSETS"
html_handling = "none"
not_found_handling = "none"

# set secrets via: wrangler secret put JWT_SECRET
# [vars]

[[d1_databases]]
binding = "KAGI_DB"
database_name = "kagi_db"
database_id = "74b1e7b2-1d8b-403c-84c1-1ee142c73c2d"
